import { ensureSchema, getRawDb } from "../../../db/runtime";
import {
  getSnapshotRow,
  materializeSnapshotCandleWindow,
} from "../../lib/snapshotStorage";
import {
  migrateDecisionLinksByBarRelation,
  type DecisionLinkBarRelation,
} from "../../lib/decisionLinkMigration";
import { isSupportedTimeframe } from "../../lib/timeframeCatalog";

type SessionEventPayload = {
  id?: string;
  sequence?: number;
  type?: string;
  barTimestamp?: number;
  payload?: unknown;
  occurredAt?: string;
};

type SessionEventRow = {
  id: string;
  sequence: number;
  type: string;
  barTimestamp: number | null;
  payloadJson: string;
  occurredAt: string;
};

type TrainingSessionMigrationRow = {
  id: string;
  dataSnapshotId: string | null;
  stateJson: string;
};

function decisionLinkLookaheadMs(timeframe: string) {
  switch (timeframe) {
    case "1m":
      return 8 * 86_400_000;
    case "5m":
    case "15m":
    case "30m":
      return 8 * 86_400_000;
    case "1h":
    case "4h":
      return 21 * 86_400_000;
    case "1d":
      return 90 * 86_400_000;
    case "1w":
      return 365 * 86_400_000;
    case "1mo":
      return 3 * 365 * 86_400_000;
    default:
      return 90 * 86_400_000;
  }
}

async function migrateStoredDecisionLinks(relation: DecisionLinkBarRelation, dryRun = false) {
  const db = getRawDb();
  const rows = await db
    .prepare(`SELECT id, data_snapshot_id AS dataSnapshotId, state_json AS stateJson
      FROM training_sessions WHERE deleted_at IS NULL`)
    .all<TrainingSessionMigrationRow>();
  const snapshotCache = new Map<string, Awaited<ReturnType<typeof getSnapshotRow>>>();
  const statements: D1PreparedStatement[] = [];
  const now = new Date().toISOString();
  let scanned = 0;
  let changedSessions = 0;
  let linkedPositions = 0;
  let linkedSubmissions = 0;
  let linkedExecutions = 0;
  let linkedPendingOrders = 0;
  let linkedMetricTrades = 0;
  let missingSnapshots = 0;
  let invalidStates = 0;

  for (const row of rows.results) {
    scanned += 1;
    let state: Record<string, unknown>;
    try {
      const parsed = JSON.parse(row.stateJson) as unknown;
      if (!parsed || typeof parsed !== "object" || Array.isArray(parsed)) throw new Error("invalid state");
      state = parsed as Record<string, unknown>;
    } catch {
      invalidStates += 1;
      continue;
    }
    const submissions = Array.isArray(state.decisionSubmissions) ? state.decisionSubmissions : [];
    const positions = Array.isArray(state.positions) ? state.positions : [];
    if (!submissions.length || !positions.some((position) => (
      position && typeof position === "object" && !Array.isArray(position)
      && !(typeof (position as Record<string, unknown>).decisionSubmissionId === "string"
        && (position as Record<string, unknown>).decisionSubmissionId)
    ))) continue;
    const snapshotId = typeof state.dataSnapshotId === "string" && state.dataSnapshotId
      ? state.dataSnapshotId
      : row.dataSnapshotId ?? "";
    if (!snapshotId) {
      missingSnapshots += 1;
      continue;
    }
    let snapshot = snapshotCache.get(snapshotId);
    if (snapshot === undefined) {
      snapshot = await getSnapshotRow(db, snapshotId);
      snapshotCache.set(snapshotId, snapshot);
    }
    if (!snapshot) {
      missingSnapshots += 1;
      continue;
    }
    const timeframe = snapshot.timeframe;
    const planTimestamps = submissions.flatMap((submission) => {
      if (!submission || typeof submission !== "object" || Array.isArray(submission)) return [];
      const value = (submission as Record<string, unknown>).barTimestamp;
      const timestamp = Number(value);
      return Number.isFinite(timestamp) ? [timestamp] : [];
    });
    if (!planTimestamps.length) continue;
    const targetPlanTimestamps = submissions.flatMap((submission) => {
      if (!submission || typeof submission !== "object" || Array.isArray(submission)) return [];
      const value = submission as Record<string, unknown>;
      if (value.autoGenerated === true || typeof value.id !== "string" || !value.id) return [];
      const timestamp = Number(value.barTimestamp);
      return Number.isFinite(timestamp) ? [timestamp] : [];
    });
    const snapshotWindows = await Promise.all(targetPlanTimestamps.map(async (timestamp) => {
      try {
        const window = await materializeSnapshotCandleWindow(db, snapshot!, {
          startTimestamp: timestamp,
          endTimestamp: Math.min(Number(snapshot!.lastTimestamp), timestamp + decisionLinkLookaheadMs(timeframe)),
        });
        return window.candles;
      } catch {
        return [];
      }
    }));
    const candleTimestamps = [...new Set(snapshotWindows.flat().map((candle) => candle.timestamp))].sort((left, right) => left - right);
    const result = migrateDecisionLinksByBarRelation(state, candleTimestamps, relation);
    if (!result.changed) continue;
    const events = Array.isArray(result.state.events)
      ? result.state.events.filter((event): event is Record<string, unknown> => Boolean(event && typeof event === "object" && !Array.isArray(event)))
      : [];
    const lastSequence = events.reduce((maximum, event) => {
      const sequence = Number(event.sequence);
      return Number.isInteger(sequence) ? Math.max(maximum, sequence) : maximum;
    }, 0);
    const migrationEvent = {
      id: crypto.randomUUID(),
      sequence: lastSequence + 1,
      type: "decision_links_migrated",
      payload: {
        rule: relation === "same-bar" ? "plan_bar_same_candle_entry" : "plan_bar_then_next_candle_entry",
        linkedPositionIds: result.linkedPositionIds,
        linkedSubmissionIds: result.linkedSubmissionIds,
        linkedExecutionCount: result.linkedExecutionCount,
        linkedPendingOrderCount: result.linkedPendingOrderCount,
        linkedMetricTradeCount: result.linkedMetricTradeCount,
      },
      occurredAt: now,
    };
    result.state.events = [...events, migrationEvent];
    const stateJson = JSON.stringify(result.state);
    if (!dryRun) {
      statements.push(
        db.prepare(`UPDATE training_sessions SET state_json = ?, updated_at = ? WHERE id = ?`)
          .bind(stateJson, now, row.id),
        db.prepare(`INSERT OR IGNORE INTO session_events
          (event_id, session_id, sequence, event_type, bar_timestamp, payload_json, occurred_at)
          VALUES (?, ?, ?, ?, ?, ?, ?)`)
          .bind(
            migrationEvent.id,
            row.id,
            migrationEvent.sequence,
            migrationEvent.type,
            null,
            JSON.stringify(migrationEvent.payload),
            migrationEvent.occurredAt,
          ),
      );
    }
    changedSessions += 1;
    linkedPositions += result.linkedPositionIds.length;
    linkedSubmissions += result.linkedSubmissionIds.length;
    linkedExecutions += result.linkedExecutionCount;
    linkedPendingOrders += result.linkedPendingOrderCount;
    linkedMetricTrades += result.linkedMetricTradeCount;
  }

  for (let index = 0; index < statements.length; index += 80) {
    await db.batch(statements.slice(index, index + 80));
  }
  return {
    scanned,
    changedSessions,
    linkedPositions,
    linkedSubmissions,
    linkedExecutions,
    linkedPendingOrders,
    linkedMetricTrades,
    missingSnapshots,
    invalidStates,
    relation,
    dryRun,
  };
}

export async function GET(request: Request) {
  await ensureSchema();
  const db = getRawDb();
  const searchParams = new URL(request.url).searchParams;
  const id = searchParams.get("id");
  const includeTrash = searchParams.get("trash") === "1";
  const visibilityClause = includeTrash ? "deleted_at IS NOT NULL" : "deleted_at IS NULL";
  if (id) {
    const session = await db
      .prepare(`SELECT id, instrument_id AS instrumentId, timeframe,
        data_snapshot_id AS dataSnapshotId, state_json AS stateJson,
        created_at AS createdAt, updated_at AS updatedAt, deleted_at AS deletedAt
        FROM training_sessions WHERE id = ? AND ${visibilityClause}`)
      .bind(id)
      .first();
    if (!session) return Response.json({ error: "训练记录不存在" }, { status: 404 });
    const events = await db
      .prepare(`SELECT event_id AS id, sequence, event_type AS type,
        bar_timestamp AS barTimestamp, payload_json AS payloadJson,
        occurred_at AS occurredAt
      FROM session_events WHERE session_id = ? ORDER BY sequence ASC`)
      .bind(id)
      .all();
    const normalizedEvents = (events.results as unknown as SessionEventRow[]).map((event) => ({
      id: event.id,
      sequence: event.sequence,
      type: event.type,
      barTimestamp: event.barTimestamp,
      payload: JSON.parse(event.payloadJson),
      occurredAt: event.occurredAt,
    }));
    return Response.json({ session, events: normalizedEvents });
  }

  const includeAll = searchParams.get("all") === "1";
  const rows = await db
    .prepare(`SELECT id, instrument_id AS instrumentId, timeframe,
      data_snapshot_id AS dataSnapshotId, state_json AS stateJson,
      created_at AS createdAt, updated_at AS updatedAt, deleted_at AS deletedAt
      FROM training_sessions WHERE ${visibilityClause}
      ORDER BY created_at DESC, id DESC${includeAll ? "" : " LIMIT 20"}`)
    .all();
  return Response.json({ sessions: rows.results });
}

export async function POST(request: Request) {
  await ensureSchema();
  const payload = (await request.json()) as {
    action?: string;
    id?: string;
    instrumentId?: string;
    timeframe?: string;
    dataSnapshotId?: string;
    dryRun?: boolean;
    state?: { events?: SessionEventPayload[] } & Record<string, unknown>;
  };
  if (payload.action === "migrate-next-bar-decision-links" || payload.action === "migrate-same-bar-decision-links") {
    const relation = payload.action === "migrate-same-bar-decision-links" ? "same-bar" : "next-bar";
    return Response.json(await migrateStoredDecisionLinks(relation, Boolean(payload.dryRun)));
  }
  if (!payload.id || !payload.instrumentId || !payload.timeframe || payload.state == null) {
    return Response.json({ error: "训练记录不完整" }, { status: 400 });
  }
  if (!isSupportedTimeframe(payload.timeframe)) {
    return Response.json({ error: `不支持的周期：${payload.timeframe}` }, { status: 400 });
  }
  const now = new Date().toISOString();
  const db = getRawDb();
  await db
    .prepare(`INSERT INTO training_sessions
      (id, instrument_id, timeframe, data_snapshot_id, state_json, created_at, updated_at)
      VALUES (?, ?, ?, ?, ?, ?, ?)
      ON CONFLICT(id) DO UPDATE SET state_json = excluded.state_json,
      instrument_id = excluded.instrument_id, timeframe = excluded.timeframe,
      data_snapshot_id = excluded.data_snapshot_id,
      updated_at = excluded.updated_at`)
    .bind(
      payload.id,
      payload.instrumentId,
      payload.timeframe,
      payload.dataSnapshotId ?? null,
      JSON.stringify(payload.state),
      now,
      now,
    )
    .run();

  const events = (payload.state.events ?? []).filter((event) =>
    event.id && Number.isInteger(event.sequence) && event.type && event.occurredAt);
  for (let index = 0; index < events.length; index += 80) {
    await db.batch(events.slice(index, index + 80).map((event) =>
      db.prepare(`INSERT OR IGNORE INTO session_events
        (event_id, session_id, sequence, event_type, bar_timestamp, payload_json, occurred_at)
        VALUES (?, ?, ?, ?, ?, ?, ?)`)
        .bind(
          event.id,
          payload.id,
          event.sequence,
          event.type,
          event.barTimestamp ?? null,
          JSON.stringify(event.payload ?? {}),
          event.occurredAt,
        )));
  }
  return Response.json({ id: payload.id, savedAt: now });
}

export async function PATCH(request: Request) {
  await ensureSchema();
  const id = new URL(request.url).searchParams.get("id");
  if (!id) return Response.json({ error: "缺少训练记录 ID" }, { status: 400 });
  const payload = (await request.json().catch(() => ({}))) as { action?: string };
  if (payload.action !== "restore") {
    return Response.json({ error: "不支持的训练记录操作" }, { status: 400 });
  }
  const now = new Date().toISOString();
  const db = getRawDb();
  const existing = await db
    .prepare("SELECT id FROM training_sessions WHERE id = ? AND deleted_at IS NOT NULL")
    .bind(id)
    .first();
  if (!existing) return Response.json({ error: "回收站中不存在这条训练记录" }, { status: 404 });
  await db
    .prepare("UPDATE training_sessions SET deleted_at = NULL, updated_at = ? WHERE id = ?")
    .bind(now, id)
    .run();
  return Response.json({ id, restored: true, restoredAt: now });
}

export async function DELETE(request: Request) {
  await ensureSchema();
  const searchParams = new URL(request.url).searchParams;
  const id = searchParams.get("id");
  if (!id) return Response.json({ error: "缺少训练记录 ID" }, { status: 400 });
  const db = getRawDb();
  const permanently = searchParams.get("permanent") === "1";
  const exists = await db.prepare("SELECT id FROM training_sessions WHERE id = ?").bind(id).first();
  if (!exists) return Response.json({ error: "训练记录不存在" }, { status: 404 });
  if (!permanently) {
    const now = new Date().toISOString();
    await db
      .prepare("UPDATE training_sessions SET deleted_at = ? WHERE id = ? AND deleted_at IS NULL")
      .bind(now, id)
      .run();
    return Response.json({ id, deleted: true, movedToTrash: true, deletedAt: now });
  }
  await db.batch([
    db.prepare("DELETE FROM session_events WHERE session_id = ?").bind(id),
    db.prepare("DELETE FROM training_sessions WHERE id = ?").bind(id),
  ]);
  return Response.json({ id, deleted: true, permanentlyDeleted: true });
}
