type MigrationRecord = Record<string, unknown>;

export type DecisionLinkMigrationResult = {
  state: MigrationRecord;
  changed: boolean;
  linkedPositionIds: string[];
  linkedSubmissionIds: string[];
  linkedExecutionCount: number;
  linkedPendingOrderCount: number;
  linkedMetricTradeCount: number;
};

export type DecisionLinkBarRelation = "next-bar" | "same-bar";

function records(value: unknown) {
  return Array.isArray(value)
    ? value.filter((item): item is MigrationRecord => Boolean(item && typeof item === "object" && !Array.isArray(item)))
    : [];
}

function finiteNumber(value: unknown) {
  const number = Number(value);
  return Number.isFinite(number) ? number : undefined;
}

function nonEmptyString(value: unknown) {
  return typeof value === "string" && value ? value : undefined;
}

function submittedAt(value: MigrationRecord) {
  return typeof value.submittedAt === "string" ? value.submittedAt : "";
}

/**
 * Attach trades that open on the selected candle relation to a plan.
 * Existing explicit links always win and are never replaced.
 */
export function migrateDecisionLinksByBarRelation(
  inputState: MigrationRecord,
  candleTimestamps: number[],
  relation: DecisionLinkBarRelation = "next-bar",
): DecisionLinkMigrationResult {
  const state: MigrationRecord = { ...inputState };
  const submissions = records(state.decisionSubmissions);
  const positions = records(state.positions).map((position) => ({ ...position }));
  const executions = records(state.executions).map((execution) => ({ ...execution }));
  const pendingOrders = records(state.pendingOrders).map((order) => ({ ...order }));
  const timestamps = candleTimestamps.filter(Number.isFinite);
  const candleIndexByTimestamp = new Map(timestamps.map((timestamp, index) => [timestamp, index]));
  const planByNextBar = new Map<number, MigrationRecord>();

  for (const submission of submissions) {
    const id = nonEmptyString(submission.id);
    const barTimestamp = finiteNumber(submission.barTimestamp);
    if (!id || barTimestamp == null || submission.autoGenerated === true) continue;
    const planIndex = candleIndexByTimestamp.get(barTimestamp);
    const candidateEntryTimestamp = relation === "same-bar"
      ? barTimestamp
      : planIndex == null ? undefined : timestamps[planIndex + 1];
    if (candidateEntryTimestamp == null) continue;
    const previous = planByNextBar.get(candidateEntryTimestamp);
    if (!previous || submittedAt(submission).localeCompare(submittedAt(previous)) >= 0) {
      planByNextBar.set(candidateEntryTimestamp, submission);
    }
  }

  const positionDecisionById = new Map<string, string>();
  const linkedPositionIds: string[] = [];
  const linkedSubmissionIds = new Set<string>();
  for (const position of positions) {
    const positionId = nonEmptyString(position.id);
    const existingDecisionId = nonEmptyString(position.decisionSubmissionId);
    if (!positionId) continue;
    if (existingDecisionId) {
      positionDecisionById.set(positionId, existingDecisionId);
      continue;
    }
    const entryTimestamp = finiteNumber(position.entryTimestamp);
    const submission = entryTimestamp == null ? undefined : planByNextBar.get(entryTimestamp);
    const submissionId = nonEmptyString(submission?.id);
    if (!submissionId) continue;
    position.decisionSubmissionId = submissionId;
    positionDecisionById.set(positionId, submissionId);
    linkedPositionIds.push(positionId);
    linkedSubmissionIds.add(submissionId);
  }

  let linkedExecutionCount = 0;
  for (const execution of executions) {
    const positionId = nonEmptyString(execution.positionId);
    const submissionId = positionId ? positionDecisionById.get(positionId) : undefined;
    if (submissionId && !nonEmptyString(execution.decisionSubmissionId)) {
      execution.decisionSubmissionId = submissionId;
      linkedExecutionCount += 1;
    }
  }

  let linkedPendingOrderCount = 0;
  for (const order of pendingOrders) {
    const positionId = nonEmptyString(order.positionId);
    const submissionId = positionId ? positionDecisionById.get(positionId) : undefined;
    if (submissionId && !nonEmptyString(order.decisionSubmissionId)) {
      order.decisionSubmissionId = submissionId;
      linkedPendingOrderCount += 1;
    }
  }

  let linkedMetricTradeCount = 0;
  const reviewMetrics = state.reviewMetrics && typeof state.reviewMetrics === "object" && !Array.isArray(state.reviewMetrics)
    ? { ...(state.reviewMetrics as MigrationRecord) }
    : undefined;
  if (reviewMetrics) {
    const metricTrades = records(reviewMetrics.trades).map((trade) => ({ ...trade }));
    for (const trade of metricTrades) {
      const positionId = nonEmptyString(trade.positionId);
      const submissionId = positionId ? positionDecisionById.get(positionId) : undefined;
      if (submissionId && !nonEmptyString(trade.decisionSubmissionId)) {
        trade.decisionSubmissionId = submissionId;
        linkedMetricTradeCount += 1;
      }
    }
    reviewMetrics.trades = metricTrades;
    state.reviewMetrics = reviewMetrics;
  }

  state.positions = positions;
  state.executions = executions;
  state.pendingOrders = pendingOrders;
  const changed = linkedPositionIds.length > 0
    || linkedExecutionCount > 0
    || linkedPendingOrderCount > 0
    || linkedMetricTradeCount > 0;
  return {
    state,
    changed,
    linkedPositionIds,
    linkedSubmissionIds: [...linkedSubmissionIds],
    linkedExecutionCount,
    linkedPendingOrderCount,
    linkedMetricTradeCount,
  };
}
